create table if not exists public.ky_user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  daily_goal integer not null default 20 check (daily_goal > 0),
  reduce_motion boolean not null default false,
  shuffle_seed text not null default '',
  settings_updated_at timestamptz,
  data_version integer not null default 1,
  updated_at timestamptz not null default now()
);

create table if not exists public.ky_word_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word_id text not null,
  status text, first_learned_at timestamptz, last_reviewed_at timestamptz,
  next_review_at timestamptz, consecutive_known integer, total_ratings integer,
  last_rating text, updated_at timestamptz not null default now(),
  unique (user_id, word_id)
);

create table if not exists public.ky_daily_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null, new_ids jsonb not null default '[]'::jsonb,
  review_ids jsonb not null default '[]'::jsonb, ratings integer not null default 0,
  completed boolean not null default false, updated_at timestamptz not null default now(),
  unique (user_id, date)
);

alter table public.ky_user_profiles enable row level security;
alter table public.ky_word_progress enable row level security;
alter table public.ky_daily_records enable row level security;
drop policy if exists "users manage own ky profile" on public.ky_user_profiles;
create policy "users manage own ky profile" on public.ky_user_profiles for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "users manage own ky word progress" on public.ky_word_progress;
create policy "users manage own ky word progress" on public.ky_word_progress for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "users manage own ky daily records" on public.ky_daily_records;
create policy "users manage own ky daily records" on public.ky_daily_records for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
grant select, insert, update, delete on public.ky_user_profiles, public.ky_word_progress, public.ky_daily_records to authenticated;
grant usage, select on sequence public.ky_word_progress_id_seq, public.ky_daily_records_id_seq to authenticated;
