"""Merge attributed and locally authored example sources into one ordered file."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "src" / "data"
ID_MAP_PATH = ROOT / "tests" / "fixtures" / "cet6-id-map-3000.json"
TATOEBA_PATH = DATA_DIR / "cet6-tatoeba-examples.json"
AUTHORED_DIR = DATA_DIR / "examples-authored"
OUTPUT_PATH = DATA_DIR / "cet6-examples.json"
MODULE_PATH = DATA_DIR / "cet6-examples.js"


def main() -> None:
    frozen = json.loads(ID_MAP_PATH.read_text(encoding="utf-8"))
    merged = {item["id"]: item for item in json.loads(TATOEBA_PATH.read_text(encoding="utf-8"))}
    authored_ids: set[str] = set()
    for path in sorted(AUTHORED_DIR.glob("*.json")):
        for item in json.loads(path.read_text(encoding="utf-8")):
            if item["id"] in authored_ids:
                raise SystemExit(f"Duplicate authored example id: {item['id']}")
            authored_ids.add(item["id"])
            merged[item["id"]] = {
                **item,
                "source": "Word Garden original",
            }
    ordered = [merged[item["id"]] for item in frozen if item["id"] in merged]
    OUTPUT_PATH.write_text(json.dumps(ordered, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    module_records = [[item["id"], [item["example"], item["exampleZh"]]] for item in ordered]
    MODULE_PATH.write_text(
        "// Generated by scripts/build-cet6-examples.py. Do not edit directly.\n"
        f"export const BILINGUAL_EXAMPLES = new Map({json.dumps(module_records, ensure_ascii=False, separators=(',', ':'))});\n",
        encoding="utf-8",
    )
    print(f"Built {len(ordered)} examples ({len(authored_ids)} original, {len(ordered) - len(authored_ids)} attributed)")


if __name__ == "__main__":
    main()
